### ISSUE TITLE
FullStack Version

### ISSUE THREAD

**Issue by fakel** [Laboratoria/FrontEnd-Questions#35]
- Actualizar lista de proyectos para coincidir con Extensión FullSatck
- Incluir problemas recomendados para FullStack
- Actualizar lista de preguntas

Fecha tope : 29/09/2021

Notas:

- Posibilidad de preguntar por PHP si han hecho proyecto WP
- Sockets para el caso de Chat APP
- CI/CD Github Actions
- Bases de datos
- Docker/Docker Compose
- Control de Versiones
- Variables de entorno
- Git/Github contribuciones
- Shell
- Escribir test teniendo código @fakel 
- Escribir código tendiendo tests @fakel 
- Corregir el error en el PR @lupomontero 
- Corregir el Bug @lupomontero 
- CORS

**Comment by lupomontero** [comment]
Habiendo ya integrado los cambios propuestos en #36 y #37, creo que podemos ir cerrando este _issue_ :smile: 

Gracias @fakel
